<?php
echo $this->headLink()
        ->prependStylesheet($this->basePath('customer/footer/css/footer.css'))
?>
<!--<link href="https://fonts.googleapis.com/css?family=Cookie|Cormorant+Upright:400,700|Dancing+Script:700|Great+Vibes|Scheherazade|Tangerine" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Cookie|Cormorant+Upright:400,700|Dancing+Script:700|Great+Vibes|Tangerine" rel="stylesheet"> -->
<div class="row">
    <div class="footer-page">  
        <!-- The content of your page would go here. -->
        <div class="footer-distributed container">
            <div class="footer-left col-xs-4">
                <h3>2SW</h3>           
            </div>

            <div class="footer-center col-xs-4">
                <h3>Contactez-nous</h3>
                <div class="">
                    <p> <a href="#" data-placement="top"
                           title="B.P. 253 Maroua; Domayo-Cameroun"><span class="glyphicon glyphicon-home">&nbsp;&nbsp;B.P.
                                253 Maroua Domayo-Cameroun;</span></a></p>
                </div>
                <div>
                    <p><a href="sahel_2sw@yahoo.fr" data-placement="top"
                          title="sahel_2sw@yahoo.fr"><span class="glyphicon glyphicon-envelope">&nbsp;&nbsp;sahel_2sw@yahoo.fr</span></a></p>
                </div>
                <div>
                    <p><a href="#" data-placement="top"
                          title="T&eacute;l&eacute;phone"><span class="glyphicon glyphicon-phone">&nbsp;&nbsp;Tél. (237) 243 59 52 46</span></a></p>
                </div>
                <div>
                    <p><a href="#" data-placement="top"
                          title="T&eacute;l&eacute;phone mobile "><span class="glyphicon glyphicon-phone-alt">&nbsp;&nbsp;675 462 512 - 696 256 367</span>
                        </a></p>
                </div>
            </div>
            <div class="footer-right col-xs-4">
                <h3>A propos de nous</h3>
                <p class="footer-company-about">
                <p class="text-primary" style="font-family: Dancing Script; font-size: 26px">Le forage de qualité c'est maintenant! </p>
                <div class="footer-icons">
                    <a href="https://facebook.com/"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('style/img/icons/social-icons/skype.png'); ?>"></span></i></a>
                    <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('style/img/icons/social-icons/youtube.png'); ?>"></span></i></a>
                    <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('style/img/icons/social-icons/twitter.png'); ?>"></span></i></a>
                    <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('style/img/icons/social-icons/facebook.png'); ?>"></span></i></a>
                    <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('style/img/icons/social-icons/evernote.png'); ?>"></span></i></a>
                    <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('style/img/icons/social-icons/linkedin.png'); ?>"></span></i></a>
                    <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('style/img/icons/social-icons/google.png'); ?>"></span></i></a>
                </div>
            </div>
        </div>
    </div>
    <div  class="row" style="background-color: white">
        <div class="container">
            <div class="col-xs-6 copyright"> Copyright © 2016 2sw All right reserved.</div>
            <div class="col-xs-1"></div>
            <div class="col-xs-5">
                <ul class="list-unstyled list-inline">
                    <li><a class="footer-menu-element" href="#">Services</a><span>&nbsp;|&nbsp;</span></li>
                    <li><a class="footer-menu-element"  href="#">Réalisations</a><span>&nbsp;|&nbsp;</span></li>
                    <li><a class="footer-menu-element" ref="#">Partenaires</a><span>&nbsp;|&nbsp;</span></li>
                    <li><a class="footer-menu-element"  href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'contact')); ?>">Contact</a><span>&nbsp;|&nbsp;</span></li>
                </ul>
            </div> 
        </div>
    </div> 
</div>


