<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html"></a>
        </div>
        <div class="navbar-collapse collapse navbar-left">
            <img src=<?php echo $this->basePath('style/img/swlogo3.PNG'); ?> alt="">
        </div>
        <div class="navbar-collapse collapse navbar-right">
            <ul class="nav navbar-nav">
                <li class="active"><a href="index.phtml">ACCUEIL</a></li>
                <li><a href="#service">SERVICES</a></li>
                <li><a href="#portfoliowrap">REALISATIONS</a></li>
                <li><a href="#cwrap">PARTENAIRES</a></li>
                <li><a href="#">ACTUALITES</a></li>
                <li><a href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'contact')); ?>">CONTACT</a></li>
                <li class="dropdown">
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>