<!DOCTYPE html>
<html lang="en">
    <head>
        <link href="style/css/style/bootstrap.min.css" rel="stylesheet" />
        <link href="style/css/style/jcarousel.css" rel="stylesheet" />
        <link href="style/css/style/flexslider.css" rel="stylesheet" />
        <link href="style/css/style/style.css" rel="stylesheet" />

    </head>
    <body class="row">
        <div>
            <!-- start header -->
            <!-- end header -->
            <!-- Slider -->
            <div id="main-slider" class="flexslider">
                <ul class="slides">
                    <li>
                        <img src="slider/img/slide1.png" alt="" />
                        <div class="flex-caption" style="margin-right: 5%">
                            <h3>Titre slide 1</h3> 
                            <p>Duis fermentum auctor ligula ac malesuada. Mauris et metus odio, in pulvinar urna</p> 
                            <a href="#" class="btn btn-theme">Learn More</a>
                        </div>
                    </li>
                    <li>
                        <img src="slider/img/slide2.png" alt="" />
                        <div class="flex-caption" style="margin-right: 5%">
                            <h3>Titre slide 2</h3> 
                            <p>Sodales neque vitae justo sollicitudin aliquet sit amet diam curabitur sed fermentum.</p> 
                            <a href="#" class="btn btn-theme">Learn More</a>
                        </div>
                    </li>
                    <li>
                        <img src="slider/img/slide3.png" alt="" />
                        <div class="flex-caption" style="margin-right: 5%">
                            <h3>Titre slide 3</h3> 
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit donec mer lacinia.</p> 
                            <a href="#" class="btn btn-theme">Learn More</a>
                        </div>
                    </li>
                    <li>
                        <img src="slider/img/slide4.png" alt="" />
                        <div class="flex-caption" style="margin-right: 5%">
                            <h3>Titre slide 4</h3> 
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit donec mer lacinia.</p> 
                            <a href="#" class="btn btn-theme">Learn More</a>
                        </div>
                    </li>
                    <li>
                        <img src="slider/img/slide5.png" alt="" />
                        <div class="flex-caption" style="margin-right: 5%">
                            <h3>Titre slide 5</h3> 
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit donec mer lacinia.</p> 
                            <a href="#" class="btn btn-theme">Learn More</a>
                        </div>
                    </li>
                </ul>
            </div>
            <!-- end slider -->
        </div>
        <a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>
        <!-- javascript
            ================================================== -->
        
        <!-- Scripts -->  
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="style/js/style/jquery.js"></script>
        <script src="style/js/style/jquery.easing.1.3.js"></script>
        <script src="style/js/style/bootstrap.min.js"></script>
        <script src="style/js/style/jquery.fancybox.pack.js"></script>
        <script src="style/js/style/jquery.fancybox-media.js"></script>
        <script src="style/js/style/jquery.flexslider.js"></script>
        <script src="style/js/style/animate.js"></script>
        <script src="style/js/style/custom.js"></script>
    </body>
</html>