<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
    <body>
       <!-- *****************************************************************************************************************
         Nos Partenaires
         ***************************************************************************************************************** -->
        <div id="cwrap">
            <div class="container">
                <div class="row centered">
                    <h3>Nos Partenaires</h3><br>
                    <div class="col-lg-4 col-md-4 col-sm-4">
                        <img src="style/img/clients/plan.png" class="img-responsive">
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4">
                        <img src="style/img/clients/bip.png" class="img-responsive">
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4">
                        <img src="style/img/clients/unicef.jpg" class="img-responsive">
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4">
                        <img src="style/img/clients/commune.png" class="img-responsive">
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4">
                        <img src="style/img/clients/snv.png" class="img-responsive">
                    </div>
                </div><! --/row -->
            </div><! --/container -->
        </div><! --/cwrap --><br>
    </body>
