<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
    <body>
        <!-- *****************************************************************************************************************
         Nos réalisations
         ***************************************************************************************************************** -->
        <div id="portfoliowrap">
            <h3>Nos réalisations</h3><br><br>
            <div class="container">
            <div class="row centered">
            <div class="col-lg-4 col-md-4 col-sm-4">
                <div class="recentitems portfolio">
                    <div class="portfolio-item graphic-design">
                        <div class="he-wrap tpl6">
                            <img src="style/img/portfolio/realisation/1.png" alt="">
                            <div class="he-view">
                                <div class="bg a0" data-animate="fadeIn">
                                    <h3 class="a1" data-animate="fadeInDown">Réalisation 1 </h3>
                                    <a data-rel="prettyPhoto" href="style/img/portfolio/realisation/1.png" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-search"></i></a>
                                    <a href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'realisation1')); ?>" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-link"></i></a>
                                </div><!-- he bg -->
                            </div><!-- he view -->		
                        </div><!-- he wrap -->
                    </div><!-- end col-12 -->

                    <div class="col-lg-4 col-md-4 col-sm-4">
                        <div class="he-wrap tpl6">
                            <img src="style/img/portfolio/realisation/2.png" alt="">
                            <div class="he-view">
                                <div class="bg a0" data-animate="fadeIn">
                                    <h3 class="a1" data-animate="fadeInDown">Réalisation 2</h3>
                                    <a data-rel="prettyPhoto" href="style/img/portfolio/realisation/2.png" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-search"></i></a>
                                    <a href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'realisation2')); ?>" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-link"></i></a>
                                </div><!-- he bg -->
                            </div><!-- he view -->		
                        </div><!-- he wrap -->
                    </div><!-- end col-12 -->

                    <div class="col-lg-4 col-md-4 col-sm-4">
                        <div class="he-wrap tpl6">
                            <img src="style/img/portfolio/realisation/3.png" alt="">
                            <div class="he-view">
                                <div class="bg a0" data-animate="fadeIn">
                                    <h3 class="a1" data-animate="fadeInDown">Réalisation 3</h3>
                                    <a data-rel="prettyPhoto" href="style/img/portfolio/realisation/3.png" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-search"></i></a>
                                    <a href="single-project.html" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-link"></i></a>
                                </div><!-- he bg -->
                            </div><!-- he view -->		
                        </div><!-- he wrap -->
                    </div><!-- end col-12 -->

                    <div class="col-lg-4 col-md-4 col-sm-4">
                        <div class="he-wrap tpl6">
                            <img src="style/img/portfolio/realisation/4.png" alt="">
                            <div class="he-view">
                                <div class="bg a0" data-animate="fadeIn">
                                    <h3 class="a1" data-animate="fadeInDown">Réalisation 4</h3>
                                    <a data-rel="prettyPhoto" href="style/img/portfolio/realisation/4.png" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-search"></i></a>
                                    <a href="#" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-link"></i></a>
                                </div><!-- he bg -->
                            </div><!-- he view -->		
                        </div><!-- he wrap -->
                    </div><!-- end col-12 -->               
                </div><!-- portfolio -->
            </div><!-- portfolio container -->
        </div><!--/Portfoliowrap -->
        </div><!-- portfolio container -->
        </div>
    </body>
