<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="style/ico/favicon.ico">

        <title>SOLID - Bootstrap 3 Theme</title>

        <!-- Bootstrap core CSS -->
        <link href="style/css/bootstrap.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="style/css/style.css" rel="stylesheet">
        <link href="style/css/font-awesome.min.css" rel="stylesheet">


        <!-- Just for debugging purposes. Don't actually copy this line! -->
        <!--[if lt IE 9]><script src="../../style/js/ie8-responsive-file-warning.js"></script><![endif]-->

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <script src="style/js/modernizr.js"></script>
    </head>

    <body>

        <!-- Fixed navbar -->
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="index.html"></a>
                </div>
                <div class="navbar-collapse collapse navbar-left">
                    <img src="style/img/swlogo3.PNG" alt="">
                </div>
                <div class="navbar-collapse collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->basePath('index.phtml'); ?>">ACCUEIL</a></li>
                        <li><a href="<?php echo $this->basePath('#service'); ?>">SERVICES</a></li>
                        <li><a href="<?php echo $this->basePath('#portfoliowrap'); ?>">REALISATIONS</a></li>
                        <li><a href="<?php echo $this->basePath('#cwrap'); ?>">PARTENAIRES</a></li>
                        <li><a href="#">ACTUALITES</a></li>
                        <li><a href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'contact')); ?>">CONTACT</a></li>
                        <li class="dropdown">
                            <!--              <a href="#" class="dropdown-toggle" data-toggle="dropdown">PAGES <b class="caret"></b></a>
                                          <ul class="dropdown-menu">
                                            <li><a href="">BLOG</a></li>
                                            <li><a href="">SINGLE POST</a></li>
                                            <li><a href="">PORTFOLIO</a></li>
                                            <li><a href="">SINGLE PROJECT</a></li>
                                          </ul>-->
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>


        <!-- *****************************************************************************************************************
         SERVICE LOGOS
         ***************************************************************************************************************** -->
        <section id="service">
            <div>
            <h3 align="center">Nos services</h3><br><br>
            <div class="container">
                <div class="row centered">
                    <div class="col-md-3">
                        <img src="style/img/icone/genciv.PNG" alt="">
                        <h4>Génie Civil</h4>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                        <p><br/><a href="#" class="btn btn-theme">More Info</a></p>
                    </div>
                    <div class="col-md-3">
                        <img src="style/img/icone/hydraulique.PNG" alt="">
                        <h4>Hydraulique</h4>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                        <p><br/><a href="#" class="btn btn-theme">More Info</a></p>
                    </div>
                    <div class="col-md-3">
                        <img src="style/img/icone/enren.PNG" alt="">
                        <h4>Energie renouvelable</h4>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                        <p><br/><a href="#" class="btn btn-theme">More Info</a></p>
                    </div>
                    <div class="col-md-3">
                        <img src="style/img/icone/ass.PNG" alt="">
                        <h4>Assainissement</h4>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                        <p><br/><a href="#" class="btn btn-theme">More Info</a></p>
                    </div>
                </div>
            </div><! --/container -->
        </div>
        </section>
        <! --/service -->

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="style/js/bootstrap.min.js"></script>
        <script src="style/js/retina-1.1.0.js"></script>
        <script src="style/js/jquery.hoverdir.js"></script>
        <script src="style/js/jquery.hoverex.min.js"></script>
        <script src="style/js/jquery.prettyPhoto.js"></script>
        <script src="style/js/jquery.isotope.min.js"></script>
        <script src="style/js/custom.js"></script>


        <script>
            // Portfolio
            (function($) {
                "use strict";
                var $container = $('.portfolio'),
                        $items = $container.find('.portfolio-item'),
                        portfolioLayout = 'fitRows';

                if ($container.hasClass('portfolio-centered')) {
                    portfolioLayout = 'masonry';
                }

                $container.isotope({
                    filter: '*',
                    animationEngine: 'best-available',
                    layoutMode: portfolioLayout,
                    animationOptions: {
                        duration: 750,
                        easing: 'linear',
                        queue: false
                    },
                    masonry: {
                    }
                }, refreshWaypoints());

                function refreshWaypoints() {
                    setTimeout(function() {
                    }, 1000);
                }

                $('nav.portfolio-filter ul a').on('click', function() {
                    var selector = $(this).attr('data-filter');
                    $container.isotope({filter: selector}, refreshWaypoints());
                    $('nav.portfolio-filter ul a').removeClass('active');
                    $(this).addClass('active');
                    return false;
                });

                function getColumnNumber() {
                    var winWidth = $(window).width(),
                            columnNumber = 1;

                    if (winWidth > 1200) {
                        columnNumber = 5;
                    } else if (winWidth > 950) {
                        columnNumber = 4;
                    } else if (winWidth > 600) {
                        columnNumber = 3;
                    } else if (winWidth > 400) {
                        columnNumber = 2;
                    } else if (winWidth > 250) {
                        columnNumber = 1;
                    }
                    return columnNumber;
                }

                function setColumns() {
                    var winWidth = $(window).width(),
                            columnNumber = getColumnNumber(),
                            itemWidth = Math.floor(winWidth / columnNumber);

                    $container.find('.portfolio-item').each(function() {
                        $(this).css({
                            width: itemWidth + 'px'
                        });
                    });
                }

                function setPortfolio() {
                    setColumns();
                    $container.isotope('reLayout');
                }

                $container.imagesLoaded(function() {
                    setPortfolio();
                });

                $(window).on('resize', function() {
                    setPortfolio();
                });
            })(jQuery);
        </script>
    </body>
</html>
