<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
    <body>
                <!-- *****************************************************************************************************************
         SERVICE LOGOS
         ***************************************************************************************************************** -->
        <section id="service">
            <div>
            <h3 align="center">Nos services</h3><br><br>
            <div class="container">
                <div class="row centered">
                    <div class="col-md-3">
                        <img src="style/img/icone/genciv.PNG" alt="">
                        <h4>Génie Civil</h4>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                        <p><br/><a href="#" class="btn btn-theme">More Info</a></p>
                    </div>
                    <div class="col-md-3">
                        <img src="style/img/icone/hydraulique.PNG" alt="">
                        <h4>Hydraulique</h4>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                        <p><br/><a href="#" class="btn btn-theme">More Info</a></p>
                    </div>
                    <div class="col-md-3">
                        <img src="style/img/icone/enren.PNG" alt="">
                        <h4>Energie renouvelable</h4>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                        <p><br/><a href="#" class="btn btn-theme">More Info</a></p>
                    </div>
                    <div class="col-md-3">
                        <img src="style/img/icone/ass.PNG" alt="">
                        <h4>Assainissement</h4>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                        <p><br/><a href="#" class="btn btn-theme">More Info</a></p>
                    </div>
                </div>
            </div><! --/container -->
        </div>
        </section>
        <! --/service -->
    </body>
